### ISSUE TITLE
Installed this to use Existing WhisperX installation Conda (that uses my Nvidia GPU) and chose GPU option, but it only uses CPU

### ISSUE THREAD

**Issue by cleverestx** [Pikurrot/whisper-gui#15] opened 2024-02-25 04:58 UTC
The Gui won't let me switch to CPU. Did I miss something? The instance of WhipserX from the command line IS using my Nvidia GPU.

I'm using Windows 11.

![image](https://github.com/Pikurrot/whisper-gui/assets/28905253/293fa374-0621-46cc-9be3-d563d9080a87)

**Comment by Pikurrot** [comment] 2024-02-25 18:22
Hi,
if you confirmed to use GPU when asked by the program, then this behavior is not expected. However, you should be able to solve it in the following way: check your `config.json` file inside the `configs` folder and make sure there is actually a field named `"gpu_support"` and is set to `true`, like this:
```
{
    "env_name": "<YOUR_ENVIRONMENT_NAME>",
    "gpu_support": true,
    "auto_update": true
}
```
Rerun the GUI and you should be able to select the "cuda" option for GPU.

Note that this will work if your environment was set up correctly and Pytorch for GPU is installed. So, if that didn't work, I suggest you select to create a new environment, as it's the recommended way. To do that, first delete the `config.json` file, then run the `whisper-gui.bat` file as if it was the first time.

Let me know if you have more trouble and, if so, attach the logs that appear in the terminal when you set up the program for the first time, so that I can know exactly when the bug appears.

I hope this helps.

**Comment by cleverestx** [comment] 2024-02-25 20:16
**Thank you for the response,** but strangely enough I don't appear to have a config.json file in that folder or anywhere else...I only have these two files in the config folder: 

![image](https://github.com/Pikurrot/whisper-gui/assets/28905253/70c687d2-e47c-48fe-a231-a8ea3afb8ad1)

Because I lack it entirely as if I "deleted" it (as per your instructions above), I ran the whisper-gui.bat

and got this error/result:

![image](https://github.com/Pikurrot/whisper-gui/assets/28905253/419465a6-5f60-4ea1-a8ef-47d6fa61f4e4)

??

**Comment by Pikurrot** [comment] 2024-02-25 23:17
Seems an error when trying to install additional dependencies. I will look into it and try to recreate the error.

**Comment by cleverestx** [comment] 2024-02-26 00:29
Thanks. Let me know if you need anything else from me.

**Comment by Pikurrot** [comment] 2024-02-26 12:06
Hi, I could replicate your error on Windows, should be solved now. I suggest you delete your `config.json` file if you had one, and run the `whisper-gui.bat` again selecting to create a new environment.

However, I realized some errors may raise due to the latest releases of some packages:
- `RuntimeError: Unsupported model binary version`: this is easy to fix, just delete the downloaded whisper model (inside `models/whisperx/` and let the GUI install the latest version of that model.
- `RuntimeError: Library cublas64_12.dll is not found or cannot be loaded`: Unfortunately, this error seems to be a problem with the latest major release of CTranslate2, which allowed support for cuda 12 but now it seems to have problems with cuda 11. I hope they fix it soon, I will stay tunned.

For now, this last error only happens on Windows for me, I had no problems running the program on Linux. Maybe you could find a workaround with WSL.

**Comment by cleverestx** [comment] 2024-02-26 15:39
Thanks for the details! I guess I'm stuck waiting for CTranslate2 to be fixed.... :-(

I can try WSL...I have Ubuntu installed, but I have WhisperX already working via command line in Windows. I guess I can reinstall everything there for now.

**Comment by Pikurrot** [comment] 2024-02-26 21:44
I've posted an issue in the CTranslate2 repo: OpenNMT/CTranslate2#1630
Let's hope they fix it soon :)

**Comment by cleverestx** [comment] 2024-02-27 19:59
I saw this elsewhere.....if it helps...

![SmartSelect_20240227_125709_Chrome](https://github.com/Pikurrot/whisper-gui/assets/28905253/e3951dd3-0807-42ed-afb3-040c63239735)

**Comment by cleverestx** [comment] 2024-02-27 23:17
I think I've already tried number 1, and it still had a problem...but I'm gonna double check that. I will let you know!

**Comment by cleverestx** [comment] 2024-02-28 06:33
Hmm, well I just ran whisper-GUI.bat and it asked me to update, and enable auto-updates and then started up. I can select CUDA now, so I guess it's all working now! :-)

**One more question..how do I set _--chunk_size 6 --task translate_ to work via this GUI for a given video/audio file?** I use that command flag often for most of the videos I process through Whisper-X. 

Thank you for all the help and info.

**Comment by Pikurrot** [comment] 2024-02-28 09:30
I'm glad it's working for you now!
About `--task translate`, it's still not an available option in the GUI, but I will take it into account for a future update, thanks for pointing it out!

I'm closing this issue as it's been solved. Feel free to open a new issue for a new suggestion for this project or if you encounter any more bugs. Thanks.

**Comment by chrisangel666** [comment] 2024-06-25 09:35
Hello, your code is very good. I would like to ask how to add localization options. I want to translate the interface into Chinese.

**Comment by chrisangel666** [comment] 2024-06-25 09:45
Also, when the subtitles and audio files are forced to align, if the wav2vec2 model of the corresponding language is selected for processing, will the effect be better than the current general model?

**Comment by chrisangel666** [comment] 2024-06-25 11:24
Every time I run the .bat file, I get this message: "torchvision is not available - cannot save figures". What is going on? Is there anything I need to do?

**Comment by Pikurrot** [comment] 2024-06-25 14:22
> Hello, your code is very good. I would like to ask how to add localization options. I want to translate the interface into Chinese.

Hi, thank you!
I also wanted to add an option to change the language. We can work on that together, if you want, just tell me and we open a discussion page in this repo and talk about it.

> Also, when the subtitles and audio files are forced to align, if the wav2vec2 model of the corresponding language is selected for processing, will the effect be better than the current general model?

Yes, I would say the transcription should be more accurate.

> Every time I run the .bat file, I get this message: "torchvision is not available - cannot save figures". What is going on? Is there anything I need to do?

This is fine, not a problem. Just a warning you can avoid by installing torchvision, but you can safely ignore it.

**Comment by chrisangel666** [comment] 2024-06-27 03:20
Nice. How to add the corresponding wav2vec2 model to the options? Does it mean to modify the corresponding item in the code? If so, how?

**Comment by Pikurrot** [comment] 2024-06-29 15:40
Wav2vec2 is an alternative, different model to Whisper. If we were to use it, we would need to add an option to choose between both, and modify some functions like _transcribe() and add a function transcribe_wav2vec2().

Are you interested in contributing?

**Comment by chrisangel666** [comment] 2024-07-06 03:55
How?

**Comment by Pikurrot** [comment] 2024-07-06 07:47
To contribute, you can fork this repo, make your own changes and then merge it with mine via pull request.
Or we can simply discuss ideas in a discussion page.

**Comment by chrisangel666** [comment] 2024-07-17 15:56
Hi, master. I have seen that you updated the whisper-gui code. How do we update it and what command is used?

**Comment by chrisangel666** [comment] 2024-07-17 16:32
Every time I turn it on, it says it can't be updated. What's going on? 
![提示](https://github.com/user-attachments/assets/e33e9120-5e03-4272-9a7c-4fd33ced60c5)
Can I update it manually using commands?

**Comment by Pikurrot** [comment] 2024-07-17 16:37
The command to update it is `git pull origin master`.
The script is trying to run `git fetch` to look for updates, but for some reason it seems to fail for you. Try manually and tell me if you can.

**Comment by chrisangel666** [comment] 2024-07-17 16:39
OK, I will try

**Comment by chrisangel666** [comment] 2024-07-17 16:42
![try](https://github.com/user-attachments/assets/ea31cdd7-0a6b-4655-9599-22fba5636a4e)
It  doesn't work

**Comment by Pikurrot** [comment] 2024-07-17 16:50
ok, you need to go first to the path where your whisper-gui repository is. You can do it with `cd path\to\your\repository` or going directly to the folder where you have it, right click and open the Terminal there.
Once you see that the path appears as `C:\....\whisper-gui`, then you can run `git pull`, or directly run the `whisper-gui.bat`, now it should work.

**Comment by chrisangel666** [comment] 2024-07-17 16:52
git pull https://github.com/Pikurrot/whisper-gui 
Should I go to the program root directory and run this command using cmd?

**Comment by Pikurrot** [comment] 2024-07-17 16:54
The URL is not necessary, but yes, from the directory where your program is

**Comment by chrisangel666** [comment] 2024-07-17 16:56
![try-2](https://github.com/user-attachments/assets/e72a1dc9-a077-48c2-b24a-7b1c237611b6)
It doesn't work

**Comment by Pikurrot** [comment] 2024-07-17 17:04
Your repository seems to have the wrong name. I don't know how you have it organized, so I suggest you clone the repo again with `git clone https://github.com/Pikurrot/whisper-gui.git` in the directory you want. Then it should work fine.
If you do this, bring your `config.json` file from the old to the new repository by manually copy-paste.  Also, if you had any saved outputs or downloaded models, bring them too (they are in folders `outputs` and `models`).
This is the easiest way I think, as I don't know your problems

**Comment by chrisangel666** [comment] 2024-07-17 17:08
OK, I'll try

**Comment by chrisangel666** [comment] 2024-07-17 17:14
![try-3](https://github.com/user-attachments/assets/48e9d8d1-5f3a-49ac-a848-88facb959fd2)

**Comment by Pikurrot** [comment] 2024-07-17 17:25
![image](https://github.com/user-attachments/assets/4e3b5e6a-ff1f-4d22-83d8-a735c66b19c5)
You should see it there.
Make sure you executed the program of the repository you just cloned, and not another one.
You cloned the repo in its latest version, and you are able to execute it. I don't know what's the issue you are having then.
Sorry I can't be of much help :(

**Comment by chrisangel666** [comment] 2024-07-17 17:28
Okay, after I delete all the files in the original folder, I run this command again and it succeed. Thank you.

**Comment by Pikurrot** [comment] 2024-07-17 17:30
Nice, glad you found the way!
I'm closing this issue now, open a new one if you ever have a different problem.
Thank you! :smiley:

**Comment by chrisangel666** [comment] 2024-07-17 17:31
It would be perfect if I could select the alignment model for the corresponding language of the audio content.

**Closed by Pikurrot** 2024-07-17 17:30 UTC
Labels: bug, documentation, enhancement

**Comment by chrisangel666** [comment] 2024-07-17 17:32
Wav2vec2

**Comment by Pikurrot** [comment] 2024-07-17 17:40
An alignment model of the same language of the transcription is already loaded automatically. It is also the language you select in "Advanced Options".
If you mean an option to use a custom alignment model, like Wav2vec2, I will take note for a future update.

**Comment by chrisangel666** [comment] 2024-07-18 13:27
Nice, can't wait to try it.

**Comment by chrisangel666** [comment] 2024-07-18 13:28
a custom alignment model, like Wav2vec2, that is pretty good.
